export const PLANS = [
  {
    id: "INICIAL",
    name: "Inicial",
    subtitle: "Primeiros passos de automatizar seu negócio.",
    price: "R$ 197",
    period: "/mês",
    features: [
      { label: "1 WhatsApp Conectado", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true },
      { label: "Disparador de campanhas", included: false },
      { label: "Rastreamento Inteligente de Links", included: false },
      { label: "Integração com Google Agenda", included: false },
      { label: "Geração de Imagem Nativa", included: false },
    ],
    popular: false,
    ctaLabel: "Começar Agora",
    color: "border-gray-200",
    headerBg: "bg-white",
  },
  {
    id: "NEGOCIOS",
    name: "Negócios 100% Automáticos",
    subtitle: "A solução completa para o seu negócio rodar sozinho.",
    price: "R$ 297",
    period: "/mês",
    features: [
      { label: "5 WhatsApp Conectados", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true },
      { label: "Disparador de campanhas", included: true },
      { label: "Rastreamento Inteligente de Links", included: true },
      { label: "Integração com Google Agenda", included: false },
      { label: "Geração de Imagem Nativa", included: false },
    ],
    popular: true,
    ctaLabel: "Testar Grátis",
    color: "border-green-500",
    headerBg: "bg-white",
  },
  {
    id: "ESCALA_TOTAL",
    name: "Escala Total",
    subtitle: "A potência máxima para grandes operações.",
    price: "R$ 397",
    period: "/mês",
    features: [
      { label: "WhatsApp Ilimitado", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true, badge: "melhorada" },
      { label: "Disparador de campanhas", included: true },
      { label: "Rastreamento Inteligente de Links", included: true },
      { label: "Integração com Google Agenda", included: true },
      { label: "Geração de Imagem Nativa", included: true },
    ],
    popular: false,
    ctaLabel: "Começar Agora",
    color: "border-gray-200",
    headerBg: "bg-white",
  },
];
