export const PLANS = [
  {
    id: "INICIAL",
    name: "Essencial",
    subtitle: "Centralize todos os seus leads e pare de perder vendas por falta de acompanhamento. Com nosso CRM, você tem a visão clara de onde cada cliente está na sua jornada, mantendo o controle total da sua base de dados.",
    price: "R$ 197",
    period: "/mês",
    features: [
      { label: "1 WhatsApp Conectado", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true },
      { label: "Disparador de campanhas", included: false },
      { label: "Rastreamento Inteligente de Links", included: false },
      { label: "Integração com Google Agenda", included: false },
      { label: "Geração de Imagem Nativa", included: false },
    ],
    popular: false,
    ctaLabel: "Começar Agora",
    color: "border-gray-200",
    headerBg: "bg-white",
  },
  {
    id: "NEGOCIOS",
    name: "Growth",
    subtitle: "Deixe de ser escravo do teclado. Nossos agentes assumem o atendimento inicial, qualificam leads e respondem dúvidas 24/7, garantindo que o toque humano apareça apenas na hora de fechar negócio.",
    price: "R$ 297",
    period: "/mês",
    features: [
      { label: "5 WhatsApp Conectados", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true },
      { label: "Disparador de campanhas", included: true },
      { label: "Rastreamento Inteligente de Links", included: true },
      { label: "Integração com Google Agenda", included: false },
      { label: "Geração de Imagem Nativa", included: false },
    ],
    popular: true,
    ctaLabel: "Testar Grátis",
    color: "border-green-500",
    headerBg: "bg-white",
  },
  {
    id: "ESCALA_TOTAL",
    name: "Performance Máxima",
    subtitle: "Domine sua estratégia com disparos em massa seguros e dashboards analíticos em tempo real. Identifique gargalos no seu funil e use dados concretos para escalar seu volume de mensagens sem risco de banimento.",
    price: "R$ 397",
    period: "/mês",
    features: [
      { label: "WhatsApp Ilimitado", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true, badge: "melhorada" },
      { label: "Disparador de campanhas", included: true },
      { label: "Rastreamento Inteligente de Links", included: true },
      { label: "Integração com Google Agenda", included: true },
      { label: "Geração de Imagem Nativa", included: true },
    ],
    popular: false,
    ctaLabel: "Começar Agora",
    color: "border-gray-200",
    headerBg: "bg-white",
  },
];
