export const PLANS = [
  {
    id: "INICIAL",
    name: "Essencial",
    subtitle: "Ideal para quem está começando a organizar o atendimento. Centralize seus leads, acompanhe cada cliente no funil e nunca mais perca uma venda por falta de follow-up. Tenha um número de WhatsApp conectado com atendente virtual por IA disponível 24 horas.",
    price: "R$ 197",
    period: "/mês",
    features: [
      { label: "1 WhatsApp Conectado", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true },
      { label: "Fluxos de Automação", included: true },
      { label: "Disparador de Campanhas", included: false },
      { label: "Rastreamento Inteligente de Links", included: false },
      { label: "Integração com Google Agenda", included: false },
      { label: "Imagem IA no Fluxo", included: false },
      { label: "Áudio IA no Fluxo (ElevenLabs)", included: false },
    ],
    popular: false,
    ctaLabel: "Começar Agora",
    color: "border-gray-200",
    headerBg: "bg-white",
  },
  {
    id: "NEGOCIOS",
    name: "Growth",
    subtitle: "Para negócios que querem escalar sem aumentar a equipe. Conecte até 5 WhatsApps, dispare campanhas segmentadas, rastreie cliques de links e deixe a IA qualificar e responder seus leads enquanto você foca em fechar negócios.",
    price: "R$ 297",
    period: "/mês",
    features: [
      { label: "5 WhatsApp Conectados", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true },
      { label: "Fluxos de Automação", included: true },
      { label: "Disparador de Campanhas", included: true },
      { label: "Rastreamento Inteligente de Links", included: true },
      { label: "Integração com Google Agenda", included: false },
      { label: "Imagem IA no Fluxo", included: false },
      { label: "Áudio IA no Fluxo (ElevenLabs)", included: false },
    ],
    popular: true,
    ctaLabel: "Começar Agora",
    color: "border-green-500",
    headerBg: "bg-white",
  },
  {
    id: "ESCALA_TOTAL",
    name: "Performance Máxima",
    subtitle: "A solução completa para operações de alto volume. WhatsApps ilimitados, IA avançada com geração de imagens e áudio nativa nos fluxos, integração com Google Agenda e todos os recursos do Growth. Escale sem limites.",
    price: "R$ 397",
    period: "/mês",
    features: [
      { label: "WhatsApp Ilimitado", included: true },
      { label: "Gestão de Clientes (CRM)", included: true },
      { label: "Atendente Virtual com IA", included: true, badge: "melhorada" },
      { label: "Fluxos de Automação", included: true },
      { label: "Disparador de Campanhas", included: true },
      { label: "Rastreamento Inteligente de Links", included: true },
      { label: "Integração com Google Agenda", included: true },
      { label: "Imagem IA no Fluxo", included: true },
      { label: "Áudio IA no Fluxo (ElevenLabs)", included: true },
    ],
    popular: false,
    ctaLabel: "Começar Agora",
    color: "border-gray-200",
    headerBg: "bg-white",
  },
];
